### ISSUE TITLE
jekyll serve

### ISSUE THREAD

**Issue by brontosaurusrex** [dyndna/lanyon-plus#12]
Os is Debian Jessie and jekyll is instaled via gem stuff
```
git clone ...
∴ticho@i5> jekyll --version
jekyll 3.4.0
~
∴ticho@i5> cd source/lanyon-plus/
~/source/lanyon-plus
∴ticho@i5> jekyll --version
/var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find i18n-0.7.0 in any of the sources (Bundler::GemNotFound)
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/spec_set.rb:80:in `map!'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/spec_set.rb:80:in `materialize'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/definition.rb:176:in `specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/definition.rb:235:in `specs_for'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/definition.rb:224:in `requested_specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:19:in `setup'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler.rb:100:in `setup'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
~/source/lanyon-plus
∵ticho@i5> cd ..
~/source
∴ticho@i5> jekyll --version
jekyll 3.4.0
```

and serve

```
∴ticho@i5> jekyll serve
/var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find i18n-0.7.0 in any of the sources (Bundler::GemNotFound)
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/spec_set.rb:80:in `map!'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/spec_set.rb:80:in `materialize'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/definition.rb:176:in `specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/definition.rb:235:in `specs_for'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/definition.rb:224:in `requested_specs'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:19:in `setup'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.4/lib/bundler.rb:100:in `setup'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
```

Thanks for your time and I would be gratefull for any hints?

**Comment by dyndna** [comment]
Sorry for missing this issue for long time. Hope you'd found a fix by now. If not, you can pull current commit: dd0fad27c965bc3c5715679eda98ab0c78a4d88a which has updated `Gemfile` and `_config.yml`. You do need to run `bundle install` from base directory of sourcecode after updating Gemfile.
